%
% M-File generated by MATLAB(R) 7.7 and the Signal Processing Toolbox 6.10.
%
% Generated on: 08-Jan-2009 12:40:15
%
%
% FIR least-squares Highpass filter designed using the FIRLS function.


% All frequency values are in Hz.
filename = 'hp_8khz';
Fs = 8000;    % Sampling Frequency
N = 300;      % Order
Fstop = 40;   % Stopband Frequency
Fpass = 70;   % Passband Frequency
Wstop = 1;    % Stopband Weight
Wpass = 1;    % Passband Weight

% Calculate the coefficients using the FIRLS function.
b = firls(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass]);

% Save to file
fid = fopen(filename,'wt');
fprintf(fid,'%1.15f\n',b);
fclose(fid);

% Plot frequency response
figure(1)
Hd = dfilt.dffir(b);
freqz(Hd.Numerator,1,16*1024,Fs)

